"""add_setting_fields

Revision ID: 9f82bf26da92
Revises: 0004
Create Date: 2026-02-08 13:17:20.499185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f82bf26da92'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ab_variants')
    op.drop_table('lead_score_rules')
    op.drop_table('segments')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_suppression_list_email', table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_table('ab_tests')
    op.alter_column('campaigns', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('uq_campaigns_name', 'campaigns', type_='unique')
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.add_column('condition_evaluation_logs', sa.Column('evaluation_result', sa.Boolean(), nullable=False))
    op.add_column('condition_evaluation_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_condition_evaluation_logs_instance_id'), 'condition_evaluation_logs', ['instance_id'], unique=False)
    op.create_index(op.f('ix_condition_evaluation_logs_node_id'), 'condition_evaluation_logs', ['node_id'], unique=False)
    op.drop_constraint('fk_condition_evaluation_logs_user_id_users', 'condition_evaluation_logs', type_='foreignkey')
    op.drop_column('condition_evaluation_logs', 'condition')
    op.drop_column('condition_evaluation_logs', 'result')
    op.drop_column('condition_evaluation_logs', 'details')
    op.drop_column('condition_evaluation_logs', 'user_id')
    op.drop_index('ix_contact_lists_owner_id', table_name='contact_lists')
    op.create_index(op.f('ix_contact_lists_name'), 'contact_lists', ['name'], unique=False)
    op.drop_index('ix_contacts_contact_list_id', table_name='contacts')
    op.add_column('email_retry_attempts', sa.Column('event_id', sa.UUID(), nullable=False))
    op.drop_index('ix_email_retry_attempts_campaign_id', table_name='email_retry_attempts')
    op.drop_index('ix_email_retry_attempts_email_send_id', table_name='email_retry_attempts')
    op.drop_index('ix_email_retry_attempts_user_id', table_name='email_retry_attempts')
    op.drop_constraint('fk_email_retry_attempts_email_send_id_email_sends', 'email_retry_attempts', type_='foreignkey')
    op.drop_constraint('fk_email_retry_attempts_campaign_id_campaigns', 'email_retry_attempts', type_='foreignkey')
    op.drop_constraint('fk_email_retry_attempts_user_id_users', 'email_retry_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_email_retry_attempts_event_id_events'), 'email_retry_attempts', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('email_retry_attempts', 'email_send_id')
    op.drop_column('email_retry_attempts', 'reason')
    op.drop_column('email_retry_attempts', 'campaign_id')
    op.drop_column('email_retry_attempts', 'user_id')
    op.add_column('email_sending_queue', sa.Column('template_id', sa.UUID(), nullable=False))
    op.alter_column('email_sending_queue', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('fk_email_sending_queue_workflow_id_workflows', 'email_sending_queue', type_='foreignkey')
    op.drop_constraint('fk_email_sending_queue_campaign_id_campaigns', 'email_sending_queue', type_='foreignkey')
    op.create_foreign_key(op.f('fk_email_sending_queue_template_id_email_templates'), 'email_sending_queue', 'email_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_email_sending_queue_campaign_id_campaigns'), 'email_sending_queue', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_column('email_sending_queue', 'html_body')
    op.drop_column('email_sending_queue', 'scheduled_for')
    op.drop_column('email_sending_queue', 'sent_at')
    op.drop_column('email_sending_queue', 'retry_count')
    op.drop_column('email_sending_queue', 'workflow_id')
    op.drop_column('email_sending_queue', 'error_message')
    op.drop_column('email_sending_queue', 'subject')
    op.drop_index('ix_email_sends_campaign_id', table_name='email_sends')
    op.drop_index('ix_email_sends_unsubscribe_token', table_name='email_sends')
    op.drop_index('ix_email_sends_user_id', table_name='email_sends')
    op.alter_column('events', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_events_type_created_at', table_name='events')
    op.drop_index('ix_events_user_id', table_name='events')
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.drop_constraint('fk_events_user_id_users', 'events', type_='foreignkey')
    op.drop_constraint('fk_events_email_send_id_email_sends', 'events', type_='foreignkey')
    op.drop_constraint('fk_events_workflow_step_id_workflow_steps', 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_user_id_users'), 'events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'workflow_step_id')
    op.drop_column('events', 'email_send_id')
    op.add_column('pipeline_items', sa.Column('stage', sa.String(length=50), nullable=False))
    op.drop_index('ix_pipeline_items_pipeline_id', table_name='pipeline_items')
    op.drop_index('ix_pipeline_items_user_id', table_name='pipeline_items')
    op.drop_constraint('fk_pipeline_items_owner_id_users', 'pipeline_items', type_='foreignkey')
    op.drop_column('pipeline_items', 'status')
    op.drop_column('pipeline_items', 'owner_id')
    op.drop_column('pipeline_items', 'notes')
    op.alter_column('settings', 'key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('settings', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('ix_settings_key', table_name='settings')
    op.create_index(op.f('ix_settings_category'), 'settings', ['category'], unique=False)
    op.create_unique_constraint(op.f('uq_settings_key'), 'settings', ['key'])
    op.alter_column('user_notes', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('fk_user_notes_created_by_id_users', 'user_notes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_notes_created_by_id_users'), 'user_notes', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_workflow_edges_workflow_id', table_name='workflow_edges')
    op.drop_index('ix_workflow_instances_user_id', table_name='workflow_instances')
    op.drop_index('ix_workflow_instances_workflow_id', table_name='workflow_instances')
    op.drop_index('ix_workflow_nodes_workflow_id', table_name='workflow_nodes')
    op.drop_index('ix_workflow_steps_instance_id', table_name='workflow_steps')
    op.drop_column('workflow_steps', 'started_at')
    op.drop_column('workflow_steps', 'error_message')
    op.drop_column('workflow_steps', 'finished_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_steps', sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('workflow_steps', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workflow_steps', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_workflow_steps_instance_id', 'workflow_steps', ['instance_id'], unique=False)
    op.create_index('ix_workflow_nodes_workflow_id', 'workflow_nodes', ['workflow_id'], unique=False)
    op.create_index('ix_workflow_instances_workflow_id', 'workflow_instances', ['workflow_id'], unique=False)
    op.create_index('ix_workflow_instances_user_id', 'workflow_instances', ['user_id'], unique=False)
    op.create_index('ix_workflow_edges_workflow_id', 'workflow_edges', ['workflow_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role_id'])
    op.drop_constraint(op.f('fk_user_notes_created_by_id_users'), 'user_notes', type_='foreignkey')
    op.create_foreign_key('fk_user_notes_created_by_id_users', 'user_notes', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_notes', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_settings_key'), 'settings', type_='unique')
    op.drop_index(op.f('ix_settings_category'), table_name='settings')
    op.create_index('ix_settings_key', 'settings', ['key'], unique=True)
    op.alter_column('settings', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('settings', 'key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('pipeline_items', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pipeline_items', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('pipeline_items', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_pipeline_items_owner_id_users', 'pipeline_items', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_pipeline_items_user_id', 'pipeline_items', ['user_id'], unique=False)
    op.create_index('ix_pipeline_items_pipeline_id', 'pipeline_items', ['pipeline_id'], unique=False)
    op.drop_column('pipeline_items', 'stage')
    op.add_column('events', sa.Column('email_send_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('workflow_step_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_events_user_id_users'), 'events', type_='foreignkey')
    op.create_foreign_key('fk_events_workflow_step_id_workflow_steps', 'events', 'workflow_steps', ['workflow_step_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_events_email_send_id_email_sends', 'events', 'email_sends', ['email_send_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_events_user_id_users', 'events', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.create_index('ix_events_user_id', 'events', ['user_id'], unique=False)
    op.create_index('ix_events_type_created_at', 'events', ['type', 'created_at'], unique=False)
    op.alter_column('events', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_email_sends_user_id', 'email_sends', ['user_id'], unique=False)
    op.create_index('ix_email_sends_unsubscribe_token', 'email_sends', ['unsubscribe_token'], unique=True)
    op.create_index('ix_email_sends_campaign_id', 'email_sends', ['campaign_id'], unique=False)
    op.add_column('email_sending_queue', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('email_sending_queue', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('email_sending_queue', sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('email_sending_queue', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('email_sending_queue', sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('email_sending_queue', sa.Column('scheduled_for', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('email_sending_queue', sa.Column('html_body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_email_sending_queue_campaign_id_campaigns'), 'email_sending_queue', type_='foreignkey')
    op.drop_constraint(op.f('fk_email_sending_queue_template_id_email_templates'), 'email_sending_queue', type_='foreignkey')
    op.create_foreign_key('fk_email_sending_queue_campaign_id_campaigns', 'email_sending_queue', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_email_sending_queue_workflow_id_workflows', 'email_sending_queue', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.alter_column('email_sending_queue', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('email_sending_queue', 'template_id')
    op.add_column('email_retry_attempts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('email_retry_attempts', sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('email_retry_attempts', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('email_retry_attempts', sa.Column('email_send_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_email_retry_attempts_event_id_events'), 'email_retry_attempts', type_='foreignkey')
    op.create_foreign_key('fk_email_retry_attempts_user_id_users', 'email_retry_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_email_retry_attempts_campaign_id_campaigns', 'email_retry_attempts', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_email_retry_attempts_email_send_id_email_sends', 'email_retry_attempts', 'email_sends', ['email_send_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_email_retry_attempts_user_id', 'email_retry_attempts', ['user_id'], unique=False)
    op.create_index('ix_email_retry_attempts_email_send_id', 'email_retry_attempts', ['email_send_id'], unique=False)
    op.create_index('ix_email_retry_attempts_campaign_id', 'email_retry_attempts', ['campaign_id'], unique=False)
    op.drop_column('email_retry_attempts', 'event_id')
    op.create_index('ix_contacts_contact_list_id', 'contacts', ['contact_list_id'], unique=False)
    op.drop_index(op.f('ix_contact_lists_name'), table_name='contact_lists')
    op.create_index('ix_contact_lists_owner_id', 'contact_lists', ['owner_id'], unique=False)
    op.add_column('condition_evaluation_logs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('condition_evaluation_logs', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('condition_evaluation_logs', sa.Column('result', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('condition_evaluation_logs', sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_condition_evaluation_logs_user_id_users', 'condition_evaluation_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_condition_evaluation_logs_node_id'), table_name='condition_evaluation_logs')
    op.drop_index(op.f('ix_condition_evaluation_logs_instance_id'), table_name='condition_evaluation_logs')
    op.drop_column('condition_evaluation_logs', 'reason')
    op.drop_column('condition_evaluation_logs', 'evaluation_result')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.create_unique_constraint('uq_campaigns_name', 'campaigns', ['name'])
    op.alter_column('campaigns', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('ab_tests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metric', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_ab_tests'),
    sa.UniqueConstraint('name', name='uq_ab_tests_name'),
    postgresql_ignore_search_path=False
    )
    op.create_table('suppression_list',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_suppression_list'),
    sa.UniqueConstraint('email', name='uq_suppression_list_email')
    )
    op.create_index('ix_suppression_list_email', 'suppression_list', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_logs_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_audit_logs')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_segments'),
    sa.UniqueConstraint('name', name='uq_segments_name')
    )
    op.create_table('lead_score_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_lead_score_rules'),
    sa.UniqueConstraint('name', name='uq_lead_score_rules_name')
    )
    op.create_table('ab_variants',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ab_test_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('traffic_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], name='fk_ab_variants_ab_test_id_ab_tests', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_ab_variants'),
    sa.UniqueConstraint('ab_test_id', 'name', name='uq_ab_variants_ab_test_name')
    )
    # ### end Alembic commands ###
